// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"

import mock "github.com/stretchr/testify/mock"

// ICommentController is an autogenerated mock type for the ICommentController type
type ICommentController struct {
	mock.Mock
}

// Delete provides a mock function with given fields: response, request
func (_m *ICommentController) Delete(response http.ResponseWriter, request *http.Request) {
	_m.Called(response, request)
}

// GetAll provides a mock function with given fields: response, request
func (_m *ICommentController) GetAll(response http.ResponseWriter, request *http.Request) {
	_m.Called(response, request)
}

// Publish provides a mock function with given fields: response, request
func (_m *ICommentController) Publish(response http.ResponseWriter, request *http.Request) {
	_m.Called(response, request)
}
