// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "go-mongo/models"

// ICommentService is an autogenerated mock type for the ICommentService type
type ICommentService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: payload
func (_m *ICommentService) Delete(payload models.CommentModel) models.APIResponseModel {
	ret := _m.Called(payload)

	var r0 models.APIResponseModel
	if rf, ok := ret.Get(0).(func(models.CommentModel) models.APIResponseModel); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(models.APIResponseModel)
	}

	return r0
}

// GetAll provides a mock function with given fields: payload
func (_m *ICommentService) GetAll(payload models.CommentModel) models.APIResponseModel {
	ret := _m.Called(payload)

	var r0 models.APIResponseModel
	if rf, ok := ret.Get(0).(func(models.CommentModel) models.APIResponseModel); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(models.APIResponseModel)
	}

	return r0
}

// Publish provides a mock function with given fields: payload
func (_m *ICommentService) Publish(payload models.CommentModel) models.APIResponseModel {
	ret := _m.Called(payload)

	var r0 models.APIResponseModel
	if rf, ok := ret.Get(0).(func(models.CommentModel) models.APIResponseModel); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(models.APIResponseModel)
	}

	return r0
}
