// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "go-mongo/models"

// IMemberService is an autogenerated mock type for the IMemberService type
type IMemberService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: payload
func (_m *IMemberService) Delete(payload models.MemberModel) models.APIResponseModel {
	ret := _m.Called(payload)

	var r0 models.APIResponseModel
	if rf, ok := ret.Get(0).(func(models.MemberModel) models.APIResponseModel); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(models.APIResponseModel)
	}

	return r0
}

// GetAll provides a mock function with given fields: payload
func (_m *IMemberService) GetAll(payload models.MemberModel) models.APIResponseModel {
	ret := _m.Called(payload)

	var r0 models.APIResponseModel
	if rf, ok := ret.Get(0).(func(models.MemberModel) models.APIResponseModel); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(models.APIResponseModel)
	}

	return r0
}

// Publish provides a mock function with given fields: payload
func (_m *IMemberService) Publish(payload models.MemberModel) models.APIResponseModel {
	ret := _m.Called(payload)

	var r0 models.APIResponseModel
	if rf, ok := ret.Get(0).(func(models.MemberModel) models.APIResponseModel); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(models.APIResponseModel)
	}

	return r0
}
